//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Game.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Game;

/**
 * Helper class for marshaling/unmarshaling PixelArray.
 **/
public final class PixelArrayHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, Pixel[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                Pixel.ice_write(ostr, v[i0]);
            }
        }
    }

    public static Pixel[] read(com.zeroc.Ice.InputStream istr)
    {
        final Pixel[] v;
        final int len0 = istr.readAndCheckSeqSize(1);
        v = new Pixel[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = Pixel.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Pixel[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, Pixel[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            PixelArrayHelper.write(ostr, v);
        }
    }

    public static java.util.Optional<Pixel[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            Pixel[] v;
            v = PixelArrayHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
