//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Game.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Game;

public class Pixel implements java.lang.Cloneable,
                              java.io.Serializable
{
    public boolean isMine;

    public Pixel()
    {
    }

    public Pixel(boolean isMine)
    {
        this.isMine = isMine;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Pixel r = null;
        if(rhs instanceof Pixel)
        {
            r = (Pixel)rhs;
        }

        if(r != null)
        {
            if(this.isMine != r.isMine)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Game::Pixel");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, isMine);
        return h_;
    }

    public Pixel clone()
    {
        Pixel c = null;
        try
        {
            c = (Pixel)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeBool(this.isMine);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.isMine = istr.readBool();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Pixel v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Pixel ice_read(com.zeroc.Ice.InputStream istr)
    {
        Pixel v = new Pixel();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Pixel> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Pixel v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(1);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<Pixel> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(Pixel.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Pixel _nullMarshalValue = new Pixel();

    /** @hidden */
    public static final long serialVersionUID = -1555718081L;
}
